name: Build and Deploy DocFX

on:
  push:
    branches:
      - master   # build only on pushes to master
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write   # <-- allow push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x   # match your project version

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build documentation
        run: |
          docfx metadata
          docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
